# Site settings
title: "{farid rener}"
email: faridrener at gmail dot com
description: A collection of Farid's notes with a scattering of food and ride reports.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.faridrener.com" # the base hostname & protocol for your site
github_username:  proteusvacuum

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax
