# Site settings
title: "Farid Rener"
email: faridrener at gmail dot com
description: A collection of Farid's notes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.faridrener.com" # the base hostname & protocol for your site
github_username:  proteusvacuum

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax

plugins:
  - jekyll-gfm-admonitions
